# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ae12edf90e4a30d09f5f31a697f59c538db04287c9587f6036eee6746a3802aa03673f9065322e61fab2383f99fbf64d796e6f190eea571194d3f9cc12e846b

test:
  secret_key_base: 4a0f5a38465b8d32ddf3dd41be9563723d0a525e5f65b136a5cf083c17e5547ca13b87d5d233ddb1eb9b2bde54d8036b046ccd0c27c98723e5153586823275a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
